import fs from 'fs';
import path from 'path';

/**
 * Saves an AI-generated audit report to the caller's project directory.
 *
 * The report is saved to `{cwd}/docs/database/auditor-query-{date}-{timestamp}.md`.
 * This function does NOT generate the report content — the AI does that.
 * It only handles persistence.
 *
 * @param reportContent - The full markdown report generated by the AI.
 * @returns The absolute path where the report was saved.
 */
export function saveAuditReport(reportContent: string): string {
  const cwd = process.cwd();
  const docsDir = path.join(cwd, 'docs', 'database');

  if (!fs.existsSync(docsDir)) {
    fs.mkdirSync(docsDir, { recursive: true });
  }

  const dateStr = new Date().toISOString().split('T')[0];
  const timestamp = Date.now();
  const filename = `auditor-query-${dateStr}-${timestamp}.md`;
  const filePath = path.join(docsDir, filename);

  fs.writeFileSync(filePath, reportContent, 'utf-8');

  return filePath;
}
