import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

/**
 * Saves an AI-generated audit report to the caller's project directory.
 *
 * The report is saved to `{cwd}/docs/database/auditor-query-{date}-{timestamp}.md`.
 * This function does NOT generate the report content — the AI does that.
 * It only handles persistence.
 *
 * @param reportContent - The full markdown report generated by the AI.
 * @returns The absolute path where the report was saved.
 */
export function saveAuditReport(reportContent: string): string {
  let cwd = process.cwd();

  // Fallback if cwd is root (common in daemon/MCP environments) or not existing
  if (cwd === '/' || !fs.existsSync(cwd)) {
    const __filename = fileURLToPath(import.meta.url);
    const __dirname = path.dirname(__filename);
    cwd = path.resolve(__dirname, '..', '..', '..', '..');
  }

  const docsDir = path.join(cwd, 'docs', 'database');

  if (!fs.existsSync(docsDir)) {
    fs.mkdirSync(docsDir, { recursive: true });
  }

  const dateStr = new Date().toISOString().split('T')[0];
  const timestamp = Date.now();
  const filename = `auditor-query-${dateStr}-${timestamp}.md`;
  const filePath = path.join(docsDir, filename);

  fs.writeFileSync(filePath, reportContent, 'utf-8');

  return filePath;
}
